"""added orders and order_items tables

Revision ID: 81f9f185fdf2
Revises: fb8ebf87d2af
Create Date: 2026-06-29 11:59:09.066801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f9f185fdf2'
down_revision: Union[str, Sequence[str], None] = 'fb8ebf87d2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
