"""Added stock column to products

Revision ID: 2781b989da10
Revises: 015c391e8796
Create Date: 2026-07-06 12:39:26.382418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2781b989da10'
down_revision: Union[str, Sequence[str], None] = '015c391e8796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
